spring.application.name=rndbet-predictions-backend

spring.config.import=optional:classpath:application-local.properties

spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.xlswyviswmgyqjcprnmb
spring.datasource.password=${SUPABASE_DB_PASSWORD:${SPRING_DATASOURCE_PASSWORD:postgres}}
